### ISSUE TITLE
exception raised for 404s

### ISSUE THREAD

**Issue by jelmer** [aio-libs/aiozipkin#410]
There is no relevant resource for 404s, yet in my case aiozipkin tries to access resource.canonical.

E.g.:

```
...
   File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_middlewares.py", line 110, in impl
     return await handler(request)
   File "/usr/local/lib/python3.7/dist-packages/aiozipkin/aiohttp_helpers.py", line 154, in aiozipkin_middleware
     _set_span_properties(span, request)
   File "/usr/local/lib/python3.7/dist-packages/aiozipkin/aiohttp_helpers.py", line 102, in _set_span_properties
     route = resource.canonical
AttributeError: 'NoneType' object has no attribute 'canonical'
```

Happy to try and submit a fix for this, if this is indeed a bug.

aiozipkin 1.1.0 on Kali Linux.

**Comment by Dreamsorcerer** [comment]
I'm not familiar with the code, but it looks like the issue was highlighted by static typing and an assert added:
https://github.com/aio-libs/aiozipkin/blame/master/aiozipkin/aiohttp_helpers.py#L102

So, probably a bug that was skipped over in a hurry. I'm not sure whether the fix needs to involve replacing the information for `route`, skipping that particular `span.tag()`, or whether the code shouldn't be running that at all (and it should be skipped at the top of the middleware).

**Comment by jelmer** [comment]
I think we'd still want to set the other properties like path, but either not set the route altogether or set it to e.g. an empty string.

**Comment by Dreamsorcerer** [comment]
Can you test out #411 and see if that works and make sense?

**Comment by jelmer** [comment]
On Mon, Jul 19, 2021 at 03:12:12PM -0700, Sam Bull wrote:
> Can you test out #411 and see if that works and make sense?
+1

That's byte for byte the workaround I've been using, which works well.
:-)

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc
